version: '3'

services:
    sandbox_king:
        build: .
        restart: always
        ports:
          - 25171:1337
        volumes:
          - ./xinetd:/etc/xinetd.d/sandbox_king:ro
        cap_add:
          - SYS_PTRACE
        security_opt:
          - seccomp:unconfined
