# Generated by Django 3.1 on 2020-09-02 04:26

from django.db import migrations
import os, codecs


def create_user(apps, schema_editor):
    User = apps.get_registered_model('auth', 'User')
    UserWallet = apps.get_model("users", "UserWallet")
    user = User(
        username='Zafir',
        password=codecs.encode(os.urandom(32), 'hex').decode('utf-8'),
    )
    user.save()
    userwallet = UserWallet(
    	user=user,
    	value=1000000000000000,
    )
    userwallet.save()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(create_user),
    ]
